// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
import ToastProvider from '@/components/providers/toaster-provider'
import { LoadingProvider } from '@/contexts/loadingContext'
import ClientWrapper from './ClientWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'K-Corp eLearning',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <LoadingProvider>
            <ConfettiProvider/>
            <ToastProvider/>
            <ClientWrapper>
              {children}
            </ClientWrapper>
          </LoadingProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}